version: "3.8"
services:
  website:
    build: .
    ports:
      - 8080:80
    volumes:
      - "./src:/var/www/html/"
    secrets:
      - user_password
    environment:
      DB_NAME: "ivresse_du_palais"
      DB_HOST: "database"
      ENVIRONMENT: "development"
    depends_on:
      - setup_db
    networks:
      - local
  database:
    image: mariadb
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: "/run/secrets/root_password"
    volumes:
      - dbdata:/var/lib/mysql
      - "./conf/.my.cnf:/root/.my.cnf"
    secrets:
      - root_password
    networks:
      - local

  setup_db:
    image: r0main/setup-wordpress-db-user
    depends_on:
      - database
    secrets:
      - root_password
      - user_password
    environment:
      DB_NAME: "ivresse_du_palais"
      DB_HOST: "database"
    networks:
      - local

networks:
  local:
    external: true
    driver: bridge
volumes:
  dbdata:
secrets:
  root_password:
    file: secrets/root_password
  user_password:
    file: secrets/db_password
